import streamlit as st

from utils import preprocess_image
from predict import predict_image

# -------------------------------
# Page Configuration
# -------------------------------
st.set_page_config(
    page_title="Chest X-ray Pneumonia Detection",
    page_icon="🩺",
    layout="centered"
)

# -------------------------------
# Sidebar
# -------------------------------
st.sidebar.title("🩺 AI Pneumonia Detection")

st.sidebar.info(
    """
This application uses an **EfficientNetB0**
deep learning model to classify
Chest X-ray images as:

✅ NORMAL

🔴 PNEUMONIA
"""
)

st.sidebar.markdown("---")
st.sidebar.write("Model : EfficientNetB0")
st.sidebar.write("Framework : TensorFlow + Streamlit")
st.sidebar.write("Image Size : 224 × 224")

# -------------------------------
# Main Title
# -------------------------------
st.title("🩺 Chest X-ray Pneumonia Detection")

st.write(
    "Upload a Chest X-ray image to predict whether it is **NORMAL** or **PNEUMONIA**."
)

st.markdown("---")

# -------------------------------
# Upload Image
# -------------------------------
uploaded_file = st.file_uploader(
    "📤 Upload Chest X-ray Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image, image_array = preprocess_image(uploaded_file)

    st.image(
        image,
        caption="Uploaded Chest X-ray",
        use_container_width=True
    )

    st.markdown("---")

    label, confidence = predict_image(image_array)

   

    # -------------------------------
    # Prediction
    # -------------------------------

    st.subheader("Prediction")

    if label == "PNEUMONIA":
        st.error(f"🔴 {label}")
    else:
        st.success(f"🟢 {label}")

    # -------------------------------
    # Confidence
    # -------------------------------

    st.subheader("Confidence Score")

    st.metric(
        label="Model Confidence",
        value=f"{confidence*100:.2f}%"
    )

    st.progress(float(confidence))

    # -------------------------------
    # Probability
    # -------------------------------

    st.subheader("Prediction Probability")

    st.write(f"**{confidence*100:.2f}%**")

    st.markdown("---")

    # -------------------------------
    # Result Summary
    # -------------------------------

    if label == "PNEUMONIA":
        st.warning(
            """
### ⚠️ Result

The uploaded Chest X-ray is predicted as **PNEUMONIA**.

Please note that this prediction is generated by an AI model and **should not be considered a medical diagnosis**.

Consult a qualified healthcare professional for confirmation.
"""
        )

    else:
        st.success(
            """
### ✅ Result

The uploaded Chest X-ray is predicted as **NORMAL**.

This prediction is generated by an AI model and **does not replace medical advice**.
"""
        )

st.markdown("---")

st.caption(
    "Developed using TensorFlow, EfficientNetB0 and Streamlit."
)
